config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'welcome#index'

  resources :flats do
    resources :pics, only: [:new, :create]
    resources :resas, only: [:new, :create]
  end
  resource :account, only: [:show, :edit, :update]

  resources :pics, only: [ :destroy ]

  resources :resas do
    patch :accept, on: :member
    patch :reject, on: :member
  end

end

app/models/flat.rb
class Flat < ActiveRecord::Base
  has_many :pics, dependent: :destroy
  belongs_to :user
  has_many :resas, dependent: :destroy
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end


end

app/models/pic.rb
class Pic < ActiveRecord::Base
  belongs_to :flat

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/resa.rb
class Resa < ActiveRecord::Base
  belongs_to :flat
  belongs_to :user

  include AASM

  aasm column: :state do
    state :pending, :initial => true
    state :accepted
    state :denied

    event :accepted do
      transitions :from => :pending, :to => :accepted
    end

    event :denied do
      transitions :from => :pending, :to => :denied
    end

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]
  has_many :flats, dependent: :destroy
  has_many :resas, dependent: :destroy

  def self.find_for_facebook_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.picture = auth.info.image # assuming the user model has an image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def show
    @account = current_user
  end

  def edit
    @account = current_user
  end

  def update
    @account = current_user
    @account.update(account_params)
    flash[:notice]="Your account is now updated"
    redirect_to account_path
  end

private
  def account_params
    params.require(:user).permit(:email, :last_name, :first_name, :address, :phone, :city)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_filter :set_flat, :only => [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @q = Flat.search(params[:q])
    @flats = @q.result(distinct: true)
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = current_user.flats.new(flat_params)
    if @flat.save
      redirect_to new_flat_pic_path(@flat)
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to new_flat_pic_path(@flat)
    else
      render action: 'edit'
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:title, :address, :description, :surface, :beds, :price, :city, :zip_code)
  end

end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  respond_to :js, :html

  def new
    @pic = Pic.new
    @flat = Flat.find(params[:flat_id])
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @flat.pics.create(pic_params)
    respond_with do |format|
      format.js
      format.html { redirect_to flat_path(@flat) }
    end
  end

  def destroy
    @pic = Pic.find(params[:id])
    @pic.destroy
    render json: {status: "OK"}
  end

  private
  def pic_params
    params.require(:pic).permit(:name, :picture)
  end

end

app/controllers/resas_controller.rb
class ResasController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]

  def new
    @flat = Flat.find(params[:flat_id])
  end

  def create
    @user = current_user
    @resa = @user.resas.create(resa_params)
    UserMailer.sending_resa(@user).deliver
    flat = Flat.find(@resa.flat_id)
    @landlord = flat.user
    UserMailer.receiving_resa(@landlord, @resa).deliver
    redirect_to account_path
  end

  def show
    @resa = Resa.find(params[:id])
  end

  def accept
    @resa = Resa.find(params[:id])
    @resa.accepted!
    redirect_to account_path
  end

  def reject
    @resa = Resa.find(params[:id])
    @resa.denied!
    redirect_to account_path
  end


  private
  def resa_params
    params.require(:resa).permit(:message, :checkin, :checkout, :flat_id)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      Rails.logger.debug '-'*50
      Rails.logger.debug @user.errors.full_messages
      Rails.logger.debug '-'*50

      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @q = Flat.search(params[:q])
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/resas_helper.rb
module ResasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/edit.html.erb
<div class="container">

  <div class="header">
    <h2>Let's edit your profile!</h2>
  </div>

  <div class="col-xs-3"></div>

  <div class="col-xs-6 container-account center-block well">
    <%=form_for @account, url: account_path, html: {role:"form"} do |f| %>
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %> <br>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control"%> <br>
      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: "form-control"  %> <br>
      <%= f.label :address %>
      <%= f.text_field  :address, class: "form-control"  %> <br>
      <%= f.label :city %>
      <%= f.text_field  :city, class: "form-control" %> <br>
      <%= f.submit "Let's edit!", :class => "btn"%>
    <% end %>
  </div>

<div class="spacer"></div>

</div>

app/views/accounts/show.html.erb
<div class="container">

  <div class="header">
    <h2>Your profile !</h2>
    <h6>All we know about you is ...:  </h6>
  </div>

  <div class="container-account center-block well col-xs-6">

      <p class="text-right"><%= link_to 'Wanna edit your profile ?', edit_account_path, class: "link" %></p>

      <div class="panel panel-default">
        <div class="panel-heading">Name:</div>
          <div class="panel-body">
            <%=current_user.first_name%>  <%=current_user.last_name%>
          </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Mail:</div>
          <div class="panel-body">
            <%=current_user.email%>
          </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">City:</div>
          <div class="panel-body">
            <%=current_user.city%>
          </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Phone:</div>
          <div class="panel-body">
            <%=current_user.phone%>
          </div>
      </div>

  </div>


  <div class="container-account center-block well col-xs-6">

      <p class="text-right"><%= link_to 'Wanna add a flat?', new_flat_path, class: "link" %></p>

      <div class="panel panel-default">
        <div class="panel-heading">Flat(s): </div>
          <div class="panel-body">
            <%current_user.flats.each do |flat|%>
             <div class= "flat_list">
                  <p><%= link_to flat.title, flat_path(flat), class: "link text-left" %>
                  <%= link_to "  Edit", edit_flat_path(flat), class: "edition" %>
                  <%= link_to "  Delete", flat, method: :delete, class: "edition" %></p>
                  <p><% flat.resas.each do |resa| %>
                    <%= link_to "You received a request from " + resa.user.email + "!", resa_path(resa), class: "edition" %></p>
                  <% end %>
            </div>
            <% end %>
          </div>
      </div>

  </div>



  <div class="container-account center-block well col-xs-6">

      <div class="panel panel-default">
        <div class="panel-heading">Resa(s): </div>
          <div class="panel-body">
            <%current_user.resas.each do |resa|%>
             <div class= "flat_list">
                  <p><%= link_to resa.flat.title, flat_path(resa.flat), class: "link" %></p>
                  <ul>
                    <li> From <%= resa.checkin %> to  <%= resa.checkout %></li>
                    <li> Status: <%= resa.state %></li>
                  </ul>
            </div>
            <% end %>
          </div>
      </div>
    </div>


  <div class="spacer"></div>

</div>

app/views/flats/_form.html.erb
<div class="col-xs-3"></div>
<div class="col-xs-6 container-flat center-block well">
  <%= form_for @flat, html: {role:"form"} do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %> <br>
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: "7" %> <br>
    <%= f.label :address %>
    <%= f.text_area :address, class: "form-control", placeholder: "10 rue Parmentier"%> <br>
    <%= f.label :city %>
    <%= f.text_area :city, class: "form-control", placeholder: "Paris, Lyon"%> <br>
    <%= f.label :zip_code %>
    <%= f.text_area :zip_code, class: "form-control", placeholder: "75011"%> <br>
    <%= f.label :surface, "Surface (m²)" %>
    <%= f.text_area :surface, class: "form-control", placeholder: "55" %> <br>
    <%= f.label :beds %>
    <%= f.text_area :beds, class: "form-control", placeholder: "2" %> <br>
    <%= f.label :price, "Price (€/night)" %>
    <%= f.text_area :price, class: "form-control", placeholder: "70"%> <br>
    <%= f.submit "Next", :class => "btn"%>
  <% end %>
</div>

app/views/flats/edit.html.erb
<div class="container">

  <div class="header">
    <h2>Let's edit the flat!</h2>
    <h6> <%= link_to "Get back to flats' list", flats_path, class: "link"%></h6>
  </div>

  <%= render "form"%>

  <div class="spacer"></div>

</div>

app/views/flats/index.html.erb
<div class="container">

  <div class="header">
    <h2>FIND A PLACE TO STAY</h2>
    <h6>Wanna add a new flat to the list?       <%= link_to 'Click here!', new_flat_path, class: 'link' %></h6>
  </div>

  <div class="container-flat center-block well">

  <% if @flats == [] %>
    <div class="text-center">
      <p>There is no flat matching to your search, try again!</p>
      <%= render 'welcome/form' %>
    </div>
  <% end %>

  <ul>
  <% @flats.each do |flat|%>
    <ol><%= link_to flat.description, flat_path(flat), class: "link" %>, <%= flat.address%>, <%= flat.price %>€/night</ol>
  <% end %>
  </ul>

  </div>

  <div class="spacer"></div>

</div>

app/views/flats/new.html.erb
<div class="container">

  <div class="header">
    <h2>Add a new flat</h2>
    <h6> <%= link_to "Get back to flats' list", flats_path, class: "link"%></h6>
  </div>

  <%= render "form"%>

  <div class="spacer"></div>

</div>

app/views/flats/show.html.erb
<div class="container">

  <div class="header">
    <h2><%=@flat.title%></h2>
    <h6> <%= link_to "Get back to flats' list", flats_path, class: "link"%></h6>
  </div>

  <div class="container-flat center-block well">

    <% if @flat.pics.size > 0 %>
    <div class="carousel_container">
      <div class="carousel">
        <h4>Pic:</h4><% @flat.pics.each do |pic| %>

            <div><%= image_tag pic.picture.url(:medium) %></div>

        <% end %>
      </div>
    </div>
    <% end %>

  <div class="wrapper_gold">
    <div class="col-sm-6 col-md-4">
      <div class="feature">
        <div class="feature-picture">
          <%= image_tag 'icon_45188.png', width: 75 %>
        </div>
          <h4>Description:</h4><%=@flat.description%>
          <h4>Address:</h4><%=@flat.address%> <%=@flat.zip_code%> <%=@flat.city%>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="feature">
        <div class="feature-picture">
          <%= image_tag 'icon_56104.png', width: 75 %>
        </div>
          <h4>Surface(m2):</h4><%=@flat.surface%>
          <h4>Beds:</h4><%=@flat.beds%>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="feature">
        <div class="feature-picture">
          <%= image_tag 'icon_22990.png', width: 75 %>
            <h4>Contact the landlord:</h4><%=@flat.user.email%>
            <h4>Price(€/night):</h4><%=@flat.price%>
        </div>
      </div>
    </div>

  </div>

      <% unless user_signed_in? && current_user.email == @flat.user.email %>
        <div class="text-right">
          <%= link_to "Let's book this flat!", new_flat_resa_path(@flat), class: "btn" %>
        </div>
      <% else %>
        <div class="text-right">
          <%= link_to "Get back to your profile!", account_path, class: "btn" %>
        </div>
      <% end %>

</div>

</div>

app/views/layouts/_sessions.html.erb
<% if user_signed_in? %>

  <li><%= link_to 'My profile', account_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>

<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path, class: "link" %></li>
  <li><%= link_to 'Sign in', new_user_session_path, class: "link" %></li>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gslapp</title>
  <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/jquery.slick/1.3.7/slick.css"/>
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>



      <!-- TODO: Here goes your content! -->

    <nav class="navbar navbar-inverse navbar-fixed-top navbar-transparent" role="navigation">
      <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <div class="navbar-brand"> <%= link_to "GSL App", root_path, class: "link" %></div>
        </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
                <%= render 'layouts/sessions' %>
            </li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Follow Us<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Linkedin</a></li>
              </ul>
            </li>
          </ul>
         </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <!-- Notice authentification -->


  <%= yield %>




        <footer>
        <div class="row">
          <div class="col-xs-12 text-right">
            <p>GSL the biggest newest app!</p>
          </div>
        </div>
      </footer>
<script type="text/javascript" src="http://cdn.jsdelivr.net/jquery.slick/1.3.7/slick.min.js"></script>


</body>
</html>

app/views/pics/_pictures.html.erb
<div class="row">
    <% @flat.pics.each do |pic| %>
      <div class="col-xs-3">
        <fieldset>
          <%= image_tag pic.picture.url(:thumb) %>
          <%= link_to "Delete", pic_path(pic), class: 'delete-picture link', method: :delete, remote: true %>
        </fieldset>
      </div>
    <% end %>
</div>

app/views/pics/create.js.erb
$("#pictures-container").html("<%= j render partial: 'pictures' %>");

app/views/pics/new.html.erb
<div class="container">

  <div class="header">
    <h2>Let's add some pictures the flat!</h2>
    <h6><%= link_to "Finish!", flat_path(@flat), class: "link text-right", id: "finish"%></h6>
  </div>
  <div id="pictures-container">
    <%= render 'pictures' %>
  </div>
  <div class="row">
    <div class="col-xs-3"></div>
      <div class="col-xs-6 container-flat center-block">
        <%= form_for [@flat, @flat.pics.new], html: { multipart: true }, :remote => true do |f| %>
            <div class="form-group">
              <%= f.label :name, "Pic name" %>
              <%= f.text_field :name, class: "form-control", placeholder: "Bedroom1" %>
            </div>
            <div class="fileUpload btn">
                <span>Upload <i class="fa fa-upload"></i></span>
                <%= f.file_field :picture, class: "upload form-control" %> <br>
            </div>
        <% end %>
      </div>
    </div>

</div>

app/views/resas/new.html.erb
<div class="container">

  <div class="header">
    <h2>Let's make a reservation!</h2>
    <h6> <%= link_to "Get back to flats' list", flats_path, class: "link"%></h6>
  </div>

    <div class="col-xs-3" ></div>
    <div class="col-xs-6 container-flat center-block well">
      <%= form_for [@flat, @flat.resas.build], html: {role:"form"} do |f| %>
        <%= f.label :message %>
        <%= f.text_area :message, class: "form-control", rows: "7" %> <br>
        <%= f.label :checkin %>
        <%= f.date_field :checkin, class: "form-control" %> <br>
        <%= f.label :checkout %>
        <%= f.date_field :checkout, class: "form-control" %> <br>
        <%= f.hidden_field :flat_id, value: params[:flat_id] %>
        <%= f.submit "Send reservation!", :class => "btn"%>
      <% end %>
    </div>

</div>

app/views/resas/show.html.erb
<div class="container">

  <div class="header">
    <h2>Here is the reservation's details!</h2>
    <h6> <%= link_to "Get back to profile", account_path, class: "link"%></h6>
  </div>

    <div class="col-xs-3" ></div>
    <div class="col-xs-6 container-flat center-block well">

      <div class="panel panel-default">
        <div class="panel-heading">From:</div>
          <div class="panel-body">
            <%= @resa.user.email %>
          </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Period:</div>
          <div class="panel-body">
            From <%= @resa.checkin %> to <%= @resa.checkout %>
          </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Message:</div>
          <div class="panel-body">
            <%= @resa.message %>
          </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Status:</div>
          <div class="panel-body">
            <%= @resa.state  %>
          </div>
      </div>

      <p class="text-center"><%= link_to "Accept", accept_resa_path, method: :patch, class: "link" %> / <%= link_to "Refuse", reject_resa_path, method: :patch, class: "link" %></p>

</div>

app/views/welcome/_form.html.erb
<%= search_form_for @q, html: {class: "form-inline", role:"form"} do |f|%>
  <%= f.label :city_matches, "City" %>
  <%= f.search_field :city_matches, class: "form-control" %>
  <%= f.submit "Go!", class: "btn" %>
<% end %>

app/views/welcome/index.html.erb
<div class="wrapper">


  <div class="container">

    <h1>WELCOME HOME</h1>

      <div class="col-xs-2"></div>
        <div class="col-xs-8 form-search">
          <p>Where do you wanna go?</p>
          <%= render 'form' %>
        </div>


  </div>

</div>